pok/urls.py
from django.contrib import admin
from django.urls import path, include


def user_views(args):
    pass


urlpatterns = [
    path('', include('pokochaj_zwierzaka.urls')),
    path('admin/', admin.site.urls),
 ]

pokochaj_zwierzaka/forms.py
from django.forms import ModelForm
from django import forms
from .models import Dog, Dopasowanie
import datetime
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User


class CreateDogForm(ModelForm):
    class Meta:
        model = Dog
        fields = ['data_urodzenia', 'rasa', 'imie', 'charakter', 'specjalne_potrzeby',
                  'choroby', 'pobyt_w_schronisku', 'fotografia']
        widgets = {
            'data_urodzenia': forms.SelectDateWidget(years=range(1998, datetime.datetime.now().year + 1)),
            'pobyt_w_schronisku': forms.SelectDateWidget(years=range(1998, datetime.datetime.now().year + 1)),
            'rasa': forms.Select(attrs={'class': 'form-control'}),
            'imie': forms.TextInput(attrs={'class': 'form-control'}),
            'charakter': forms.Textarea(attrs={'class': 'form-control'}),
            'specjalne_potrzeby': forms.Textarea(attrs={'class': 'form-control'}),
            'choroby': forms.Textarea(attrs={'class': 'form-control'})

        }


class CreateDopasowanieForm(ModelForm):
    class Meta:
        model = Dopasowanie
        fields = ['wiek_psa', 'rasa_psa', 'czas_pobytu_w_schronisku', 'pies_ze_specjalnymi_wymaganiami',
                  'pies_z_chorobami']
        widgets = {
            'wiek_psa': forms.Select(attrs={'class': 'form-control'}),
            'rasa_psa': forms.Select(attrs={'class': 'form-control'}),
            'czas_pobytu_w_schronisku': forms.Select(attrs={'class': 'form-control'}),
            'pies_ze_specjalnymi_wymaganiami': forms.Select(attrs={'class': 'form-control'}),
            'pies_z_chorobami': forms.Select(attrs={'class': 'form-control'})
        }


class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(max_length=100,
                                    widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(max_length=100,
                                    widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


  </head>
  <body>
        <div class="container">
        {%  block content %}

        {%  endblock %}
        </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/change-password.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <title>POK Logowanie</title>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
</head>
<body>

{% block content %}
    <div class="limiter">
        <div class="container-glowna">
            <div class="wrap-glowna">
                <h1>Zmiana hasła</h1>
                <br/><br/>
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        <p><label for="id_old_password">Stare Hasło:</label> <input type="password" name="old_password"
                                                                                    class="form-control" required
                                                                                    id="id_old_password"></p>
                        <p><label for="id_new_password1">Nowe Hasło:</label> <input type="password" name="new_password1"
                                                                                    class="form-control" maxlength="100"
                                                                                    required id="id_new_password1"></p>
                        <p><label for="id_new_password2">Powtórz Hasło:</label> <input type="password"
                                                                                       name="new_password2"
                                                                                       class="form-control"
                                                                                       maxlength="100" required
                                                                                       id="id_new_password2"></p>
                        <button class="btn btn-secondary">Zmień hasło
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/create_dog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!DOCTYPE html>
    <html lang="pl">
    <head>
        <title>POK Dodaj psa</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/create_dog.css' %}">
        <link rel="icon" href="{% static 'images/lapka.png' %}">
        <script type="text/javascript" src="{% static 'js/glowna.js' %}"></script>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    </head>


    <body>
    <div class="limiter-nav">
        <div class="container-nav">
            <div class="wrap-nav">
                <div class="nav">
                    <ul>
                        <li>
                            <img src="{% static 'images/lapka.png' %}" alt="IMG">
                        </li>
                        <li>
                            <p>Pokochaj<br>zwierzaka</p>
                        </li>
                        <li><p><a href="{% url 'home' %}">Baza psów</a></p></li>
                        {% if request.user.groups.all.0.name == 'schronisko' %}
                            <li><p><a href="{% url 'create_dog' %}">Dodaj psa</a></p></li>
                            <div>
                                <li><p><a href="{% url 'twoje_psy' %}">Twoje psy</a></p></li>
                            </div>
                        {% else %}
                            <li><p><a href="{% url 'matching' %}">Dopasuj do siebie psa</a></p></li>
                        {% endif %}
                        <li>
                            <div class="container-nav-btn">
                                <button class="nav-btn">
                                    <a href="profile">Twoje konto</a>
                                </button>
                            </div>
                            <div class="container-nav-btn">
                                <button class="nav-btn">

                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}">Wyloguj się</a>
                                    {% else %}
                                        <a href="{% url 'index' %}">Zaloguj się</a>
                                    {% endif %}

                                </button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="limiter">
        <div class="container-glowna">
            <div class="wrap-glowna">
                <div class="form-group">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ create_dog_form.as_p }}
                        <input type="submit" value="Dodaj psa" class="btn btn-secondary">
                    </form>

                </div>
            </div>
        </div>
    </div>
    </body>
    </html>

{% endblock %}

templates/custom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>user is created </h1>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <title>POK Strona Główna</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/glowna.css' %}">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
    <script type="text/javascript" src="{% static 'js/glowna.js' %}"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>

<div class="limiter-nav">
    <div class="container-nav">
        <div class="wrap-nav">
            <div class="nav">
                <ul>
                    <li>
                        <img src="{% static 'images/lapka.png' %}" alt="IMG">
                    </li>
                    <li>
                        <p>Pokochaj<br>zwierzaka</p>
                    </li>
                    <li><p><a href="{% url 'home' %}">Baza psów</a></p></li>
                    {% if request.user.groups.all.0.name == 'schronisko' %}
                        <li><p><a href="{% url 'create_dog' %}">Dodaj psa</a></p></li>
                        <div>
                            <li><p><a href="{% url 'twoje_psy' %}">Twoje psy</a></p></li>
                        </div>
                    {% else %}
                        <li><p><a href="{% url 'matching' %}">Dopasuj do siebie psa</a></p></li>
                    {% endif %}
                    <li>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                <a href="profile">Twoje konto</a>
                            </button>
                        </div>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                {% block content %}
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}">Wyloguj się</a>
                                    {% else %}
                                        <a href="{% url 'index' %}">Zaloguj się</a>
                                    {% endif %}
                                {% endblock %}
                            </button>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="limiter">
    <div class="container-glowna">
        <div class="wrap-glowna">

           {% for item in all %}
               <div class="zdj">
                   <a target="_blank" href="{{ item.fotografia }}">
                                <img src="{{ item.fotografia }}"/><br>
                   </a>
               </div>
               <div class="dogs-glowna">
               Imie: {{ item.imie }} <br>
               Data urodzenia: {{ item.data_urodzenia }} <br>
               Rasa: {{ item.rasa }} <br>
               Charakter: {{ item.charakter }} <br>
               Specjalne potrzeby: {{ item.specjalne_potrzeby }} <br>
               Choroby: {{ item.choroby }} <br>
               Pobyt w schronisku od: {{ item.pobyt_w_schronisku }} <br>
               Schronisko: {{ item.shelter }} <br>
                   <hr>
               </div>

            {% endfor %}
        </div>
    </div>
</div>


<button onclick="topFunction()" id="myBtn" title="Go to top">
    <img src="{% static 'images/strzalka.png' %}" alt="IMG">
</button>
</div>
</body>
</html>

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="pl">
<head>
	<title>POK Logowanie</title>
	<meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/logowanie.css' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/lapka.png' %}" alt="IMG">
				</div>

				<form action = "" class="login100-form validate-form" , method = 'POST'>
					{% csrf_token %}

					<span class="login100-form-title">
						Logowanie
					</span>



					<div class="wrap-input100 validate-input" data-validate = "username must be 4 to 8 character">
						<input class="input100" type="text" name="username" placeholder="Login">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Hasło">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Zaloguj się
						</button>
					</div>
					<div class="alert">
						{% for message in messages %}
						<h3>{{message}}</h3>
						{%endfor%}
					</div>
                    <div class="XD">
                    </div>
					<div class="text-center p-t-136">
						<a class="txt2" href="{{'register'}}">
							Stwórz nowe konto
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'js/main.js' %} "></script>

</body>
</html>

templates/matching.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!DOCTYPE html>
    <html lang="pl">
    <head>
        <title>POK Dodaj psa</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/matching.css' %}">
        <link rel="icon" href="{% static 'images/lapka.png' %}">
        <script type="text/javascript" src="{% static 'js/glowna.js' %}"></script>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    </head>


    <body>
    <div class="limiter-nav">
        <div class="container-nav">
            <div class="wrap-nav">
                <div class="nav">
                    <ul>
                        <li>
                            <img src="{% static 'images/lapka.png' %}" alt="IMG">
                        </li>
                        <li>
                            <p>Pokochaj<br>zwierzaka</p>
                        </li>
                        <li><p><a href="{% url 'home' %}">Baza psów</a></p></li>
                        {% if request.user.groups.all.0.name == 'schronisko' %}
                            <li><p><a href="{% url 'create_dog' %}">Dodaj psa</a></p></li>
                            <div>
                                <li><p><a href="{% url 'twoje_psy' %}">Twoje psy</a></p></li>
                            </div>
                        {% else %}
                            <li><p><a href="{% url 'matching' %}">Dopasuj do siebie psa</a></p></li>
                        {% endif %}
                        <li>
                            <div class="container-nav-btn">
                                <button class="nav-btn">
                                    <a href="profile">Twoje konto</a>
                                </button>
                            </div>
                            <div class="container-nav-btn">
                                <button class="nav-btn">

                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}">Wyloguj się</a>
                                    {% else %}
                                        <a href="{% url 'index' %}">Zaloguj się</a>
                                    {% endif %}

                                </button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="limiter">
        <div class="container-glowna">
            <div class="wrap-glowna">
                <div class="form-group">

                    <form method="post">
                        {% csrf_token %}
                        {{ create_dopasowanie_form.as_p }}
                        <input type="submit" value="Użyj narzędzia dopasowania" class="btn btn-secondary">
                    </form>

                </div>
            </div>
        </div>
    </div>
    </body>
    </html>

{% endblock %}

templates/profile.html
{% load static %}
<!DOCTYPE html>

<html lang="pl">
<head>
    <title>POK Profil</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profil.css' %}">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
    <script type="text/javascript" src="{% static 'js/profil.js' %}"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>

<div class="limiter-nav">
    <div class="container-nav">
        <div class="wrap-nav">
            <div class="nav">
                <ul>
                    <li>
                        <img src="{% static 'images/lapka.png' %}" alt="IMG">
                    </li>
                    <li>
                        <p>Pokochaj<br>zwierzaka</p>
                    </li>
                    <li><p><a href="{% url 'home' %}">Baza psów</a></p></li>
                    {% if request.user.groups.all.0.name == 'schronisko' %}
                        <li><p><a href="{% url 'create_dog' %}">Dodaj psa</a></p></li>
                        <div>
                            <li><p><a href="{% url 'twoje_psy' %}">Twoje psy</a></p></li>
                        </div>
                        {% else %}
                        <li><p><a href="{% url 'matching' %}">Dopasuj do siebie psa</a></p></li>
                    {% endif %}
                    <li>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                <a href="profile">Twoje konto</a>
                            </button>
                        </div>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                {%  block content %}
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}">Wyloguj się</a>
                                    {% else %}
                                        <a href="{% url 'index' %}">Zaloguj się</a>
                                    {% endif %}
                                {%  endblock %}
                            </button>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper">
    <div class="left">
        <img src="{% static 'images/user.png' %}" alt="IMG"
        alt="user" width="100">
        <h4></h4>
         <p><h2>Witaj {{ user.username }}!</h2></p>
    </div>
    <div class="right">
        <div class="info">
            <h2>Informacje</h2>
            <div class="info_data">
                 <div class="data">
                    <h4>Email</h4>
                    <h5>{{ user.email }}</h5>
                     <h6><a href="{% url 'password' %}">Zmień hasło</a></h6>
                     <h6><a href="{% url 'logout' %}">Wyloguj się</a></h6>
                     {% if request.user.groups.all.0.name != 'schronisko' %}
                            <li>
                                 <button id="schroniska">Kontakt dla schronisk</button>
                                 <p id="tresc"></p>
                            </li>
                     {% endif %}
                 </div>
            </div>
        </div>
    </div>
</div>
<script>
    var s= document.getElementById('schroniska'),
        tresc = document.getElementById('tresc');

    s.onclick = function() {
        tresc.innerHTML = 'Aby uzyskać prawa do dodawania psów skontaktuj sie z nami pod adresem e-mail: pokzwierzaka@gmail.com lub telefonicznie tel: xxx-xxx-xxx';
    }
</script>
</body>
</html>

templates/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>POK Rejestracja</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
</head>
<body>




	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/lapka.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" , method = 'POST'>
					{% csrf_token %}

					<span class="login100-form-title">
						Rejestracja
					</span>

					<div class="wrap-input100 validate-input" >
						<input class="input100" type="email"  name="email" placeholder="Email" required>
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text"  minlength="4"  maxlength="12"  name="username" placeholder="Login" required >
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" minlength="4"  maxlength="12" name="password" placeholder="Hasło" required >
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							zarejestruj się
						</button>
					</div>
                    					<div class="alert">
						{% for message in messages %}
						<h3>{{message}}</h3>
						{%endfor%}
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'js/main.js' %} "></script>

</body>
</html>

templates/twoje_psy.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <title>POK Strona Główna</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/glowna.css' %}">
    <link rel="icon" href="{% static 'images/lapka.png' %}">
    <script type="text/javascript" src="{% static 'js/glowna.js' %}"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>
{% if request.user.groups.all.0.name == 'schronisko' %}
<div class="limiter-nav">
    <div class="container-nav">
        <div class="wrap-nav">
            <div class="nav">
                <ul>
                    <li>
                        <img src="{% static 'images/lapka.png' %}" alt="IMG">
                    </li>
                    <li>
                        <p>Pokochaj<br>zwierzaka</p>
                    </li>
                    <li><p><a href="{% url 'home' %}">Baza psów</a></p></li>
                    {% if request.user.groups.all.0.name == 'schronisko' %}
                        <li><p><a href="{% url 'create_dog' %}">Dodaj psa</a></p></li>
                        <div>
                            <li><p><a href="{% url 'twoje_psy' %}">Twoje psy</a></p></li>
                        </div>
                    {% else %}
                        <li><p><a href="{% url 'matching' %}">Dopasuj do siebie psa</a></p></li>
                    {% endif %}
                    <li>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                <a href="profile">Twoje konto</a>
                            </button>
                        </div>
                        <div class="container-nav-btn">
                            <button class="nav-btn">
                                {% block content %}
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}">Wyloguj się</a>
                                    {% else %}
                                        <a href="{% url 'index' %}">Zaloguj się</a>
                                    {% endif %}
                                {% endblock %}
                            </button>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="limiter">
    <div class="container-glowna">
        <div class="wrap-glowna">
           {% for item in all %}
                    {% if item.shelter_id == user.id %}
                       <div class="zdj">
                           <a target="_blank" href="{{ item.fotografia }}">
                                        <img src="{{ item.fotografia }}"/><br>
                           </a>
                       </div>
                        <div class="dogs-glowna">
                        Imie: {{ item.imie }} <br>
                        Data Urodzenia: {{ item.data_urodzenia }} <br>
                        Rasa: {{ item.rasa }} <br>
                        Charakter: {{ item.charakter }} <br>
                        Specjalne potrzeby: {{ item.specjalne_potrzeby }} <br>
                        Choroby: {{ item.choroby }} <br>
                        Pobyt w schronisku od: {{ item.pobyt_w_schronisku }} <br>
                        Schronisko: {{ item.shelter }} <br>
                        <hr>
                        </div>
                    {% endif %}
                {% endfor %}
        </div>
    </div>
</div>



<button onclick="topFunction()" id="myBtn" title="Go to top">
    <img src="{% static 'images/strzalka.png' %}" alt="IMG">
</button>

{% else %}
    <h6>Niestety nie masz dostępu do tej strony</h6>
{% endif %}
</body>
</html>